apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-ttyd
  name: k8s-ttyd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-ttyd
  strategy: {}
  template:
    metadata:
      labels:
        app: k8s-ttyd
    spec:
      containers:
        - image: dhub.inerplat.com/inerplat/ttyd:arm64
          imagePullPolicy: Always
          name: k8s-ttyd
          tty: true
          stdin: true
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          lifecycle:
            postStart:
              exec:
                command: [
                  "/bin/bash",
                  "-c",
                  "/bin/entrypoint.sh"
                ]
