apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-ttyd
  name: k8s-ttyd
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: k8s-ttyd
  type: ClusterIP
